const vendor = {
  name: "Anjappar Wimbledon",
  slug: "anjappar-wimbledon",
  domain: "anjappar.co.uk",
  logo: "anjappar-logo.png",
  theme: "chettinad",
  address: "12 High Street, Wimbledon, London SW19 5DX",
  cuisine: ["South Indian", "Chettinad", "Tamil"],
  currency: "INR",
  currencySymbol: "₹",
  seoDefaults: {
    titleTemplate: "{restaurantName} Menu - {categoryName}",
    defaultDescription: "Explore authentic South Indian and Chettinad cuisine at Anjappar Wimbledon.",
    defaultImage: "anjappar-og.jpg",
    keywords: ["south indian restaurant", "chettinad food", "wimbledon takeaway"],
  },
  widgetConfig: {
    showSearch: true,
    showRecommendations: true,
    showVegFilter: true,
    showStockStatus: true,
    ctaLabel: "Order Now",
    itemsPerPage: 12,
  },
  isActive: true,
};

const categories = [
  {
    name: "Starters",
    slug: "starters",
    description: "Light bites and appetisers to begin your meal",
    image: "cat-starters.jpg",
    sortOrder: 1,
    isFeatured: true,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "starters",
  },
  {
    name: "Veg Starters",
    slug: "veg-starters",
    description: "Delicious vegetarian appetisers",
    image: "cat-veg-starters.jpg",
    sortOrder: 2,
    isFeatured: false,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "veg-starters",
    _parentRef: "starters",
  },
  {
    name: "Non-Veg Starters",
    slug: "non-veg-starters",
    description: "Succulent meat and seafood starters",
    image: "cat-nonveg-starters.jpg",
    sortOrder: 3,
    isFeatured: false,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "non-veg-starters",
    _parentRef: "starters",
  },
  {
    name: "South Indian Mains",
    slug: "south-indian-mains",
    description: "Authentic South Indian rice, dosa and curry dishes",
    image: "cat-mains.jpg",
    sortOrder: 4,
    isFeatured: true,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "mains",
  },
  {
    name: "Breads",
    slug: "breads",
    description: "Fresh-baked Indian breads from our tandoor",
    image: "cat-breads.jpg",
    sortOrder: 5,
    isFeatured: false,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "breads",
  },
  {
    name: "Rice & Biryani",
    slug: "rice-biryani",
    description: "Fragrant rice dishes and slow-cooked biryanis",
    image: "cat-biryani.jpg",
    sortOrder: 6,
    isFeatured: true,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "rice",
  },
  {
    name: "Desserts",
    slug: "desserts",
    description: "Traditional Indian sweets and desserts",
    image: "cat-desserts.jpg",
    sortOrder: 7,
    isFeatured: false,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "desserts",
  },
  {
    name: "Drinks",
    slug: "drinks",
    description: "Refreshing Indian beverages and soft drinks",
    image: "cat-drinks.jpg",
    sortOrder: 8,
    isFeatured: false,
    isPublished: true,
    isDeleted: false,
    parentId: null,
    _ref: "drinks",
  },
];

const products = [
  // Veg Starters
  {
    name: "Samosa (4)",
    slug: "samosa-4",
    brand: "House Special",
    description: "Golden, crispy pastry filled with spiced potato mixture, deep-fried to perfection. Served with mint chutney.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 40,
    storePrice: 30,
    priceDiscount: 0,
    priceDiscounted: 40,
    openingStock: 50,
    currentStock: 50,
    tags: ["crispy", "potato", "pastry", "street food", "budget", "golden", "fried"],
    spiceLevel: "mild",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "veg-starters",
  },
  {
    name: "Paneer Tikka",
    slug: "paneer-tikka",
    brand: "House Special",
    description: "Cubes of fresh cottage cheese marinated in spiced yoghurt, grilled in our tandoor oven. Smoky, tender and flavourful.",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 350,
    storePrice: 300,
    priceDiscount: 0,
    priceDiscounted: 350,
    openingStock: 30,
    currentStock: 30,
    tags: ["paneer", "grilled", "tandoor", "spicy", "cottage cheese", "smoky"],
    spiceLevel: "medium",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "veg-starters",
  },
  {
    name: "Gobi 65",
    slug: "gobi-65",
    brand: "House Special",
    description: "Crispy cauliflower florets deep-fried with South Indian spices, curry leaves and green chillies. A Chettinad classic.",
    image: "https://images.pexels.com/photos/35071824/pexels-photo-35071824.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 60,
    storePrice: 50,
    priceDiscount: 10,
    priceDiscounted: 60,
    openingStock: 40,
    currentStock: 40,
    tags: ["cauliflower", "crispy", "spicy", "south indian", "chettinad"],
    spiceLevel: "hot",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "veg-starters",
  },
  {
    name: "Onion Bhaji (4)",
    slug: "onion-bhaji-4",
    brand: "House Special",
    description: "Crispy fried onion fritters seasoned with cumin, coriander and green chillies. Light, golden and moreish.",
    image: "https://images.pexels.com/photos/17390930/pexels-photo-17390930.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 40,
    storePrice: 30,
    priceDiscount: 0,
    priceDiscounted: 40,
    openingStock: 60,
    currentStock: 0,
    tags: ["onion", "crispy", "fried", "budget", "fritter", "golden"],
    spiceLevel: "mild",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "veg-starters",
  },
  {
    name: "Mushroom 65",
    slug: "mushroom-65",
    brand: "House Special",
    description: "Button mushrooms tossed in a fiery South Indian spice blend, fried until crisp.",
    image: "https://images.pexels.com/photos/35267270/pexels-photo-35267270.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 60,
    storePrice: 50,
    priceDiscount: 0,
    priceDiscounted: 60,
    openingStock: 35,
    currentStock: 35,
    tags: ["mushroom", "spicy", "crispy", "south indian", "vegetarian"],
    spiceLevel: "hot",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "veg-starters",
  },
  // Non-Veg Starters
  {
    name: "Chicken 65",
    slug: "chicken-65",
    brand: "House Special",
    description: "Crispy boneless chicken pieces marinated in a fiery South Indian spice paste with curry leaves.",
    image: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=500&q=75",
    isVeg: false,
    isNonVeg: true,
    price: 70,
    storePrice: 60,
    priceDiscount: 0,
    priceDiscounted: 70,
    openingStock: 40,
    currentStock: 40,
    tags: ["chicken", "crispy", "spicy", "chettinad", "boneless"],
    spiceLevel: "hot",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "non-veg-starters",
  },
  {
    name: "Seekh Kebab",
    slug: "seekh-kebab",
    brand: "House Special",
    description: "Minced lamb mixed with aromatic spices and herbs, skewered and grilled over charcoal. Juicy and smoky.",
    image: "https://images.pexels.com/photos/37080242/pexels-photo-37080242.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: false,
    isNonVeg: true,
    price: 400,
    storePrice: 350,
    priceDiscount: 0,
    priceDiscounted: 400,
    openingStock: 25,
    currentStock: 25,
    tags: ["lamb", "kebab", "grilled", "charcoal", "smoky"],
    spiceLevel: "medium",
    mealType: ["starter", "sharing"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "non-veg-starters",
  },
  {
    name: "Prawn Koliwada",
    slug: "prawn-koliwada",
    brand: "House Special",
    description: "Juicy prawns coated in a tangy spiced batter and deep-fried until golden. A coastal Indian favourite.",
    image: "https://images.pexels.com/photos/15476833/pexels-photo-15476833.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: false,
    isNonVeg: true,
    price: 600,
    storePrice: 550,
    priceDiscount: 0,
    priceDiscounted: 600,
    openingStock: 20,
    currentStock: 20,
    tags: ["prawn", "seafood", "crispy", "coastal", "fried"],
    spiceLevel: "medium",
    mealType: ["starter"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "non-veg-starters",
  },
  // Mains
  {
    name: "Masala Dosa",
    slug: "masala-dosa",
    brand: "House Special",
    description: "A large crispy rice and lentil crepe filled with spiced potato masala. Served with sambar and two chutneys.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 90,
    storePrice: 80,
    priceDiscount: 0,
    priceDiscounted: 90,
    openingStock: 30,
    currentStock: 30,
    tags: ["dosa", "crispy", "rice crepe", "potato", "south indian", "classic", "family friendly"],
    spiceLevel: "mild",
    mealType: ["main"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "mains",
  },
  {
    name: "Chettinad Chicken Curry",
    slug: "chettinad-chicken-curry",
    brand: "House Special",
    description: "Slow-cooked chicken in an aromatic Chettinad masala with kalpasi, star anise and stone flower.",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&q=75",
    isVeg: false,
    isNonVeg: true,
    price: 150,
    storePrice: 120,
    priceDiscount: 30,
    priceDiscounted: 150,
    openingStock: 25,
    currentStock: 25,
    tags: ["chicken", "curry", "chettinad", "slow cooked", "aromatic", "spicy"],
    spiceLevel: "hot",
    mealType: ["main"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "mains",
  },
  {
    name: "Dal Tadka",
    slug: "dal-tadka",
    brand: "House Special",
    description: "Yellow lentils slow-cooked with turmeric and finished with a smoky ghee tadka of cumin, garlic and dried red chillies.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 80,
    storePrice: 60,
    priceDiscount: 0,
    priceDiscounted: 80,
    openingStock: 40,
    currentStock: 40,
    tags: ["lentil", "dal", "vegetarian", "comfort food", "budget"],
    spiceLevel: "mild",
    mealType: ["main"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "mains",
  },
  {
    name: "Idli Sambar (3 pieces)",
    slug: "idli-sambar",
    brand: "House Special",
    description: "Soft steamed rice and lentil cakes served with hot sambar and coconut chutney. Light, healthy and filling.",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 50,
    storePrice: 40,
    priceDiscount: 0,
    priceDiscounted: 50,
    openingStock: 50,
    currentStock: 50,
    tags: ["idli", "steamed", "healthy", "light", "south indian", "kids"],
    spiceLevel: "none",
    mealType: ["main", "kids"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "mains",
  },
  // Breads
  {
    name: "Garlic Naan",
    slug: "garlic-naan",
    brand: "House Special",
    description: "Soft leavened bread topped with minced garlic and butter, baked in our tandoor oven.",
    image: "https://images.pexels.com/photos/10337726/pexels-photo-10337726.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 100,
    storePrice: 90,
    priceDiscount: 0,
    priceDiscounted: 100,
    openingStock: 100,
    currentStock: 100,
    tags: ["naan", "bread", "garlic", "tandoor", "butter", "soft"],
    spiceLevel: "none",
    mealType: ["side"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "breads",
  },
  {
    name: "Parotta",
    slug: "parotta",
    brand: "House Special",
    description: "Flaky, layered South Indian flatbread made with maida, folded into layers and cooked on a griddle.",
    image: "https://images.pexels.com/photos/10810650/pexels-photo-10810650.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 15,
    storePrice: 13,
    priceDiscount: 0,
    priceDiscounted: 15,
    openingStock: 80,
    currentStock: 80,
    tags: ["parotta", "bread", "flaky", "south indian", "layered"],
    spiceLevel: "none",
    mealType: ["side"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "breads",
  },
  // Rice & Biryani
  {
    name: "Chicken Biryani",
    slug: "chicken-biryani",
    brand: "House Special",
    description: "Fragrant basmati rice slow-cooked with tender chicken pieces, saffron and caramelised onions. Served with raita.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=75",
    isVeg: false,
    isNonVeg: true,
    price: 150,
    storePrice: 140,
    priceDiscount: 0,
    priceDiscounted: 150,
    openingStock: 20,
    currentStock: 20,
    tags: ["biryani", "chicken", "rice", "saffron", "slow cooked", "premium","family"],
    spiceLevel: "medium",
    mealType: ["main", "sharing"],
    isPublished: true,
    isDeleted: false,
    isFeatured: true,
    _categoryRef: "rice",
  },
  {
    name: "Vegetable Biryani",
    slug: "vegetable-biryani",
    brand: "House Special",
    description: "Aromatic basmati rice cooked with seasonal vegetables, saffron and dum spices. Light and fragrant.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 120,
    storePrice: 110,
    priceDiscount: 0,
    priceDiscounted: 120,
    openingStock: 25,
    currentStock: 25,
    tags: ["biryani", "vegetarian", "rice", "saffron", "aromatic"],
    spiceLevel: "mild",
    mealType: ["main"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "rice",
  },
  // Desserts
  {
    name: "Gulab Jamun (2)",
    slug: "gulab-jamun",
    brand: "House Special",
    description: "Soft milk-solid dumplings soaked in rose and cardamom sugar syrup. Served warm.",
    image: "https://images.pexels.com/photos/14610769/pexels-photo-14610769.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 50,
    storePrice: 40,
    priceDiscount: 0,
    priceDiscounted: 50,
    openingStock: 60,
    currentStock: 60,
    tags: ["sweet", "dessert", "rose", "syrup", "soft", "warm", "kids"],
    spiceLevel: "none",
    mealType: ["dessert", "kids"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "desserts",
  },
  {
    name: "Rasmalai (2)",
    slug: "rasmalai-2",
    brand: "House Special",
    description: "Spongy paneer discs soaked in chilled saffron and cardamom milk. Topped with pistachios.",
    image: "https://images.pexels.com/photos/33430555/pexels-photo-33430555.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 55,
    storePrice: 40,
    priceDiscount: 0,
    priceDiscounted: 55,
    openingStock: 30,
    currentStock: 30,
    tags: ["sweet", "dessert", "saffron", "chilled", "paneer", "pistachio"],
    spiceLevel: "none",
    mealType: ["dessert"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "desserts",
  },
  // Drinks
  {
    name: "Mango Lassi",
    slug: "mango-lassi",
    brand: "House Special",
    description: "Thick, chilled yoghurt drink blended with ripe Alphonso mango pulp and a hint of cardamom.",
    image: "https://images.pexels.com/photos/17200460/pexels-photo-17200460.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 40,
    storePrice: 30,
    priceDiscount: 0,
    priceDiscounted: 40,
    openingStock: 50,
    currentStock: 50,
    tags: ["mango", "lassi", "drink", "chilled", "sweet", "refreshing", "budget"],
    spiceLevel: "none",
    mealType: ["drink"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "drinks",
  },
  {
    name: "Masala Chai",
    slug: "masala-chai",
    brand: "House Special",
    description: "Spiced Indian tea brewed with ginger, cardamom, cinnamon and cloves in full-fat milk.",
    image: "https://images.pexels.com/photos/10377676/pexels-photo-10377676.jpeg?auto=compress&cs=tinysrgb&w=500&q=75",
    isVeg: true,
    isNonVeg: false,
    price: 30,
    storePrice: 15,
    priceDiscount: 0,
    priceDiscounted: 30,
    openingStock: 100,
    currentStock: 100,
    tags: ["tea", "chai", "spiced", "warm", "ginger", "cardamom", "budget"],
    spiceLevel: "mild",
    mealType: ["drink"],
    isPublished: true,
    isDeleted: false,
    isFeatured: false,
    _categoryRef: "drinks",
  },
];

module.exports = { vendor, categories, products };